/**
 * Build script: reads the disposable-email-detector domain list,
 * builds a bloom filter, writes raw binary + typed metadata.
 *
 * Run via: npx tsx scripts/build-filter.ts
 */

import { BloomFilter } from "../src/bloom";
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));

// Load the disposable domain list from the dev dependency
const listPath = resolve(__dirname, "../node_modules/disposable-email-domains/index.json");
const rawList: string[] = JSON.parse(readFileSync(listPath, "utf-8"));

// Normalize: lowercase, trim
const domains = [...new Set(rawList.map((d) => d.toLowerCase().trim()))];
const n = domains.length;

const TARGET_FP_RATE = 0.0001; // 0.01%

const filter = BloomFilter.fromItems(domains, TARGET_FP_RATE);

// Ensure output directory exists
const outDir = resolve(__dirname, "../src/generated");
mkdirSync(outDir, { recursive: true });

// Write raw binary filter
writeFileSync(resolve(outDir, "filter.bin"), filter.data);

// Write typed metadata
const meta = `// Auto-generated by scripts/build-filter.ts — do not edit
export const BIT_COUNT: number = ${filter.bitCount};
export const HASH_COUNT: number = ${filter.hashCount};
export const ITEM_COUNT: number = ${n};
`;
writeFileSync(resolve(outDir, "filter-meta.ts"), meta);

// Print summary
const fpRate = filter.estimatedFpRate(n);
console.log(`
╔══════════════════════════════════════════════════╗
║         Bloom Filter Build Summary               ║
╠══════════════════════════════════════════════════╣
║  Items:         ${n.toLocaleString().padStart(10)}                    ║
║  Bit count:     ${filter.bitCount.toLocaleString().padStart(10)}                    ║
║  Hash count:    ${filter.hashCount.toString().padStart(10)}                    ║
║  Byte size:     ${filter.byteSize.toLocaleString().padStart(10)}                    ║
║  Est. FP rate:  ${fpRate.toExponential(3).padStart(10)}                    ║
╚══════════════════════════════════════════════════╝
`);
