/**
 * Build script: fetches the disposable domain list from GitHub,
 * builds a bloom filter, writes raw binary + typed metadata.
 *
 * Run via: npx tsx scripts/build-filter.ts
 */

import { BloomFilter } from "../src/bloom";
import { writeFileSync, mkdirSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));

const DOMAINS_URL =
	"https://raw.githubusercontent.com/disposable/disposable-email-domains/master/domains.txt";

console.log(`Fetching domain list from ${DOMAINS_URL} ...`);
const response = await fetch(DOMAINS_URL);
if (!response.ok) {
	throw new Error(`Failed to fetch domain list: ${response.status} ${response.statusText}`);
}
const text = await response.text();
const rawList = text.split("\n").filter(Boolean);

// Normalize: lowercase, trim
const domains = [...new Set(rawList.map((d) => d.toLowerCase().trim()))].filter(Boolean);
const n = domains.length;

const TARGET_FP_RATE = 0.0001; // 0.01%

const filter = BloomFilter.fromItems(domains, TARGET_FP_RATE);

// Ensure output directory exists
const outDir = resolve(__dirname, "../src/generated");
mkdirSync(outDir, { recursive: true });

// Write raw binary filter
writeFileSync(resolve(outDir, "filter.bin"), filter.data);

// Write typed metadata
const meta = `// Auto-generated by scripts/build-filter.ts — do not edit
export const BIT_COUNT: number = ${filter.bitCount};
export const HASH_COUNT: number = ${filter.hashCount};
export const ITEM_COUNT: number = ${n};
`;
writeFileSync(resolve(outDir, "filter-meta.ts"), meta);

// Print summary
const fpRate = filter.estimatedFpRate(n);
console.log(`
╔══════════════════════════════════════════════════╗
║         Bloom Filter Build Summary               ║
╠══════════════════════════════════════════════════╣
║  Items:         ${n.toLocaleString().padStart(10)}                    ║
║  Bit count:     ${filter.bitCount.toLocaleString().padStart(10)}                    ║
║  Hash count:    ${filter.hashCount.toString().padStart(10)}                    ║
║  Byte size:     ${filter.byteSize.toLocaleString().padStart(10)}                    ║
║  Est. FP rate:  ${fpRate.toExponential(3).padStart(10)}                    ║
╚══════════════════════════════════════════════════╝
`);
